version: "2"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: digit:dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
